name: Clockwork Espresso
favicon: null
layout_spectrum: 0.9766333161387593
typography_spectrum: 0.7462292700074613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5399213822092861
  lightness: 0.9086707106325775
  saturation: 0.30436420370824635
  rhythmicContrast: 0.7130734755191952
purpose: []
